# ===============================
# Spring Boot Application
# ===============================
spring.application.name=resume-builder

# ===============================
# PostgreSQL Database (Render)
# ===============================
spring.datasource.url=jdbc:postgresql://dpg-d9d1s3ihil2s73b4875g-a.singapore-postgres.render.com:5432/resume_builder_alob
spring.datasource.username=user
spring.datasource.password=cPZfyVEXGFySILTVVog9o2jkWE4mq8JS
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Server Port
# ===============================
server.port=8080