spring.application.name=resume-builder
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/resume_builder
spring.datasource.username=resume
spring.datasource.password=resume
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update
